### ISSUE TITLE
Error con Foreing key

### ISSUE THREAD

**Issue by diazrafael** [delacrmi/android_orm#1]
`09-08 01:29:33.174 5038-5038/com.adriantech.usuario.clientecrud D/creating: Creando
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err: java.lang.Exception: The column id don't exist in  the relationship table
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.Entity.getColumnByRelation(Entity.java:164)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.Entity.getCreateString(Entity.java:134)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.setCreateString(EntityManager.java:153)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.access$000(EntityManager.java:18)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager$1.beforeToCreate(EntityManager.java:87)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.ConnectSQLite.onCreate(ConnectSQLite.java:49)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.read(EntityManager.java:128)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.init(EntityManager.java:107)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.adriantech.usuario.clientecrud.MainActivity.initDB(MainActivity.java:138)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.adriantech.usuario.clientecrud.MainActivity.onCreate(MainActivity.java:51)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.Activity.performCreate(Activity.java:5104)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:141)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.os.Looper.loop(Looper.java:137)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5041)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at dalvik.system.NativeStart.main(Native Method)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err: java.lang.NullPointerException
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityProperty.setTableName(EntityProperty.java:54)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityProperty.<init>(EntityProperty.java:42)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.Entity.setPropertyTable(Entity.java:521)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.Entity.getCreateString(Entity.java:105)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.setCreateString(EntityManager.java:153)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.access$000(EntityManager.java:18)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager$1.beforeToCreate(EntityManager.java:87)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.ConnectSQLite.onCreate(ConnectSQLite.java:49)
09-08 01:29:33.194 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.read(EntityManager.java:128)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.delacrmi.simorm.EntityManager.init(EntityManager.java:107)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.adriantech.usuario.clientecrud.MainActivity.initDB(MainActivity.java:138)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.adriantech.usuario.clientecrud.MainActivity.onCreate(MainActivity.java:51)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.Activity.performCreate(Activity.java:5104)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:141)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.os.Looper.loop(Looper.java:137)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5041)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
09-08 01:29:33.204 5038-5038/com.adriantech.usuario.clientecrud W/System.err:     at dalvik.system.NativeStart.main(Native Method)
09-08 01:29:33.214 5038-5038/com.adriantech.usuario.clientecrud D/AndroidRuntime: Shutting down VM
09-08 01:29:33.214 5038-5038/com.adriantech.usuario.clientecrud W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb24fc908)
09-08 01:29:33.214 5038-5038/com.adriantech.usuario.clientecrud E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adriantech.usuario.clientecrud/com.adriantech.usuario.clientecrud.MainActivity}: java.lang.NullPointerException
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: java.lang.NullPointerException
                                                                                      at com.delacrmi.simorm.EntityProperty.setTableName(EntityProperty.java:54)
                                                                                      at com.delacrmi.simorm.EntityProperty.<init>(EntityProperty.java:42)
                                                                                      at com.delacrmi.simorm.Entity.setPropertyTable(Entity.java:521)
                                                                                      at com.delacrmi.simorm.Entity.getProperty(Entity.java:179)
                                                                                      at com.delacrmi.simorm.EntityManager.executeAfterTrigger(EntityManager.java:163)
                                                                                      at com.delacrmi.simorm.EntityManager.access$100(EntityManager.java:18)
                                                                                      at com.delacrmi.simorm.EntityManager$1.afterToCreate(EntityManager.java:92)
                                                                                      at com.delacrmi.simorm.ConnectSQLite.onCreate(ConnectSQLite.java:51)
                                                                                      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                                                      at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                                      at com.delacrmi.simorm.EntityManager.read(EntityManager.java:128)
                                                                                      at com.delacrmi.simorm.EntityManager.init(EntityManager.java:107)
                                                                                      at com.adriantech.usuario.clientecrud.MainActivity.initDB(MainActivity.java:138)
                                                                                      at com.adriantech.usuario.clientecrud.MainActivity.onCreate(MainActivity.java:51)
                                                                                      at android.app.Activity.performCreate(Activity.java:5104)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                                      at dalvik.system.NativeStart.main(Native Method) 
`
**Entidad 1**
`package com.adriantech.usuario.clientecrud.Entity;

import com.delacrmi.simorm.annotation.Column;
import com.delacrmi.simorm.annotation.OneToOne;
import com.delacrmi.simorm.annotation.Table;

@Table
public class Cliente extends com.delacrmi.simorm.Entity {

```
@Column(NotNull = true,
        PrimaryKey = true,
        AutoIncrement = true)
public int id;

@Column(NotNull = true)
public String fullName;

@Column
public String email;

@Column
public String telefono;

@Column
@OneToOne(ForeingKey = {"ID"})
public Direccion direccion;

public Cliente() {
}

public Cliente(int id, String fullName, String email, String telefono) {
    this.id = id;
    this.fullName = fullName;
    this.email = email;
    this.telefono = telefono;
}

public Cliente(int id, String fullName, String email) {
    this.id = id;
    this.fullName = fullName;
    this.email = email;
}

//
public Cliente(String fullName, String email) {
    this.fullName = fullName;
    this.email = email;
}

//
public Cliente(String fullName) {
    this.fullName = fullName;
}
```

}
`

**Entidad 2**

`package com.adriantech.usuario.clientecrud.Entity;

import com.delacrmi.simorm.Entity;
import com.delacrmi.simorm.annotation.Column;
import com.orm.dsl.Table;

/**
- Created by Usuario on 06/09/2016.
  */
  @Table
  public class Direccion extends Entity{
  
  @Column(NotNull = true,
          PrimaryKey = true,
          AutoIncrement = true)
  public int id;
  
  @Column(NotNull = true)
  public String calle;
  
  @Column
  public String casa;
  
  public Direccion(String calle, String casa) {
      this.calle = calle;
      this.casa = casa;
  }
  
  public Direccion() {
  }
  }
  `

**Iniciando EntityManager**
`    private void initDB() {
        //setup the EntityManager
        EntityManager manager = new EntityManager(getApplicationContext(), "prueba", null, 2);
        //Adding a new persistence
        manager.addEntity(Direccion.class);
        manager.addEntity(Cliente.class);

```
    //Starting the manager
    manager.init();
}`
```

**Comment by delacrmi** [comment]
En la entidad 2 hay un error en el **import** de la anotación **@Table** debe ser **import com.delacrmi.simorm.annotation.Table;**

La excepción es porque no esta encontrando la columna **id** de la clase **Direccion** en la clase **Cliente**, trata de actualizar la versión de  la base de datos para que cree la columna de la relación.

### Iniciando EntityManager

``` java
private void initDB() {
        //setup the EntityManager
        new EntityManager(getApplicationContext(), "prueba", null, 3)
                .addEntity(Cliente.class)
                .addEntity(Direccion.class).init();
}
```

### Direccion.class

``` java
package com.adriantech.usuario.clientecrud.Entity;

import com.delacrmi.simorm.Entity;
import com.delacrmi.simorm.annotation.Column;
import com.delacrmi.simorm.annotation.OneToOne;
import com.delacrmi.simorm.annotation.Table;

@Table
public class Direccion extends Entity<Direccion> {
    @Column(NotNull = true,
            PrimaryKey = true,
            AutoIncrement = true)
    public int id;

    @Column(NotNull = true)
    public String calle;

    @Column public String casa;

    //Create a map to cliente class without to save this column
    @OneToOne(ForeingKey = {"direccion"}, Create = false)
    @Column public Cliente cliente;

    public Direccion(String calle, String casa) {
        this.calle = calle;
        this.casa = casa;
    }

    public Direccion() {}
}
```

### Cliente.class

``` java
package com.adriantech.usuario.clientecrud.Entity;

import com.delacrmi.simorm.annotation.Column;
import com.delacrmi.simorm.annotation.OneToOne;
import com.delacrmi.simorm.annotation.Table;

@Table
public class Cliente extends com.delacrmi.simorm.Entity<Cliente> {

    @Column(NotNull = true,
            PrimaryKey = true,
            AutoIncrement = true)
    public int id;

    @Column(NotNull = true)
    public String fullName;

    @Column
    public String email;

    @Column
    public String telefono;

    @Column
    @OneToOne(ForeingKey = {"id"})
    public Direccion direccion;

    public Cliente() {}

    public Cliente(int id, String fullName, String email, String telefono) {
        this.id = id;
        this.fullName = fullName;
        this.email = email;
        this.telefono = telefono;
    }

    public Cliente(int id, String fullName, String email) {
        this.id = id;
        this.fullName = fullName;
        this.email = email;
    }

    public Cliente(String fullName, String email) {
        this.fullName = fullName;
        this.email = email;
    }

    public Cliente(String fullName) {
        this.fullName = fullName;
    }
}
```
